---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: my-app
          image: springboot-docker-kubernetes:1.0
          ports:
            - containerPort: 8082