pipeline {
    agent any

    tools{
        maven '3.6.3'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        steps {
                 sh 'mvn -Dmaven.test.failure.ignore=true install'
               }
        post {
              success {
                  junit 'target/surefire-reports/**/*.xml'
              }
        }
        stage('Deploy') {
                    when {
                      expression {
                        currentBuild.result == null || currentBuild.result == 'SUCCESS'
                      }
                    }
                    steps {
                        sh 'make publish'
                    }
                }
    }
}