pipeline{
    agent any
    stages {
        stage('Compile Stage'){
            withMaven(maven: '3.6.3_1'){
                sh mvn clean compile
            }
        }
        stage('Test Stage'){
             withMaven(maven: '3.6.3_1'){
                 sh mvn test
             }
        }
        stage('Deploy Stage'){
              withMaven(maven: '3.6.3_1'){
                  sh mvn deploy
              }
        }
    }
}